### PR TITLE
Disallow comma when zero decimal places and improve error message

### LINKED ISSUE #56: Improve error message for input type "number"
**Device:** Honor View 20
**OS:** Android 10
**App version:**  5d71b14

**Issue (How to reproduce):**
If you type a number in a form field, which is out of the expected range (as it can be seen in the screenshot), the error message doesn't respect the amount of allowed decimal places. Also, if the maximum allowed number isn't set, it is displayed in the error message as "Infinity".

**Expected behavior:**
The expected error message (in this case) should be something like: "Wert muss größer sein als 1".

Screenshot with visualized stop areas

Thanks @rebeccasc for the hint.

### PR DESCRIPTION
**Pull request by 7h30n3**
Fixes #56 and #55

### CODE REVIEW

File: lib/widgets/question_inputs/number_input.dart [hunk 1]
```diff
@@ -18,8 +18,8 @@ class NumberInput extends QuestionInputView {
 class _NumberInputState extends State<NumberInput> {
   final _controller = TextEditingController();
 
-  late double _minValue;
-  late double _maxValue;
+  late int? _minValue;
+  late int? _maxValue;
```
Comment (Robbendebiene) [inline lib/widgets/question_inputs/number_input.dart:22]: We can now replace these variables with `widget.questionInput.min` and `widget.questionInput.max` (just use them directly like we already do with `widget.questionInput.decimals`)


Therefore we can drop multiple code lines:

```dart
  late int? _minValue;
  late int? _maxValue;

  @override
  void initState() {
    super.initState();
    _updateMinMax();
  }


  @override
  void didUpdateWidget(covariant NumberInput oldWidget) {
    super.didUpdateWidget(oldWidget);
    _updateMinMax();
  }

void _updateMinMax() {
    _minValue = widget.questionInput.min;
    _maxValue = widget.questionInput.max;
  }

```

File: lib/widgets/question_inputs/number_input.dart [hunk 2]
```diff
@@ -83,19 +91,36 @@ class _NumberInputState extends State<NumberInput> {
...
+      return false;
+    }
+    return true;
+  }
+
+
+  RegExp _buildRegex() {
+    var regexString = '^\\d+';
+    if (widget.questionInput.decimals != null && widget.questionInput.decimals! > 0) {
+      regexString += '[\\,.]?\\d{0,${widget.questionInput.decimals}}';
```
Comment (Robbendebiene) [inline lib/widgets/question_inputs/number_input.dart:120]: Are the \\ inside `[\\,.]` relay necessary? I think this should work without them too.

**Review by Robbendebiene — COMMENTED** [review]
Can you please add 2-3 comments (using 3 slashes: ///) in the `question_input` model above the decimal, max and min variable definitions and explain the consequence of these variables being null.
